name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm install
      - run: npm run prod
      - name: Deploy
        env: 
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}
          DESTINATION: ${{ secrets.DESTINATION }}
        run: |
          mkdir -p ~/.ssh
          echo "$SECRET_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          rsync -av --delete --rsync-path="sudo rsync" \
            --exclude=".git*" \
            --exclude=".vscode" \
            --exclude="public/storage" \
            --exclude="node_modules" \
            --exclude="src" \
            --exclude="storage" \
            --exclude="vendor" \
            --exclude=".env*" \
            --exclude=".babelrc" \
            --exclude=".editorconfig" \
            --exclude=".eslintrc.json" \
            --exclude=".prettierrc" \
            --exclude=".styleci.yml" \
            --exclude="package.json" \
            --exclude="package-lock.json" \
            --exclude="README.md" \
            --exclude="tsconfig.json" \
            -e ssh . ${USER}@${HOST}:${DESTINATION}
