name: CI

on:
  push:
    branches: [ main ]

jobs:
  laravel-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer install --prefer-dist
      - name: Copy env
        run: cp .env.example .env
      - name: Generate key
        run: php artisan key:generate
      - name: Create cache directory
        run: mkdir storage/app/cache
      - name: Run test
        run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: [ laravel-test ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Build SPA
        run: |
          npm install
          npm run prod
      - name: Setup SSH
        env: 
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SECRET_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - name: Deploy rsync
        env: 
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}
          DESTINATION: ${{ secrets.DESTINATION }}
        run: |
          rsync -av --delete --rsync-path="sudo rsync" \
            --exclude=".git*" \
            --exclude=".vscode" \
            --exclude="public/storage" \
            --exclude="node_modules" \
            --exclude="src" \
            --exclude="storage" \
            --exclude="vendor" \
            --exclude=".env*" \
            --exclude=".babelrc" \
            --exclude=".editorconfig" \
            --exclude=".eslintrc.json" \
            --exclude=".prettierrc" \
            --exclude=".styleci.yml" \
            --exclude="package.json" \
            --exclude="package-lock.json" \
            --exclude="README.md" \
            --exclude="tsconfig.json" \
            -e ssh . ${USER}@${HOST}:${DESTINATION}
      - name: Deploy migration
        env: 
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}
          DESTINATION: ${{ secrets.DESTINATION }}
        run: |
          ssh -i ~/.ssh/any-press.pem github@118.27.5.185 bash -c "'
            cd /var/www/html/laravel
            sudo composer install --optimize-autoloader --no-dev
            sudo php artisan migrate --force
            sudo php artisan cache:clear
            sudo php artisan config:clear
            sudo php artisan route:clear
            sudo php artisan view:clear
            sudo php artisan config:cache
            sudo php artisan route:cache
            sudo php artisan view:cache
          '"
